# Generated by Django 5.2.2 on 2025-07-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uuid',
            new_name='id',
        ),
    ]
